frontend:
   build: ./frontend/
   ports:
    - "8765:80"
   volumes:
    - ./frontend:/opt/frontend/
   links:
    - "api:backend"
    - "mongo:database"
api:
   build: ./api/
   ports:
    - "8080"
   volumes:
    - ./api:/opt/api/
   links:
    - "mongo:database"
mongo:
   image: mongo:latest
   volumes:
    - ./data:/data/db
   ports:
    - "27017"
